# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ticTacToe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ticTacToe
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7.0'


  target 'ticTacToeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ticTacToe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ticTacToe-tvOS

  target 'ticTacToe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
